version: '3.8'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - "15672:15672"
  nest-shop:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
      args:
        - --target=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    command: npm run start:dev nest-shop --watch
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq
      - redis
  auth:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      - rabbitmq
    command: npm run start:dev auth --watch
  product:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      - rabbitmq
    command: npm run start:dev product --watch
  health:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      - rabbitmq
    command: npm run start:dev health --watch
  notifications:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      - rabbitmq
    command: npm run start:dev notifications --watch
  category:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      - rabbitmq
    command: npm run start:dev category --watch
  cart:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      - rabbitmq
    command: npm run start:dev cart --watch
  payment:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      - rabbitmq
    command: npm run start:dev payment --watch
  support:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      - rabbitmq
    command: npm run start:dev support --watch
networks:
  default:
    driver: bridge